SCR_JournalSetupConfig {
 m_iJournalEntryToShowOnStart 0
 m_aJournals {
  SCR_JournalConfig "{646847056DB82144}" {
   m_FactionKey "US"
   m_aEntries {
    SCR_JournalEntry "{646847056DB826BE}" {
     m_iEntryID 1
     m_sCustomEntryName "#AR-RespawnMap_FRAGO_SituationTitle"
     m_sEntryText "#AR-Briefing_CO_Arland_Situation_B_US"
    }
    SCR_JournalEntry "{646847056DB826BC}" {
     m_iEntryID 2
     m_eJournalEntryType Mission
     m_sCustomEntryName "#AR-RespawnMap_FRAGO_MissionTitle"
     m_sEntryText "#AR-Briefing_CO_Arland_Mission_US"
    }
    SCR_JournalEntry "{646847056DB826B2}" {
     m_iEntryID 3
     m_eJournalEntryType Execution
     m_sCustomEntryName "#AR-RespawnMap_FRAGO_ExecutionTitle"
     m_sEntryText "#AR-Briefing_CO_Arland_Execution_US"
    }
    SCR_JournalEntry "{646847056DB826B3}" {
     m_iEntryID 4
     m_eJournalEntryType Signal
     m_sCustomEntryName "#AR-RespawnMap_FRAGO_SignalTitle"
     m_sEntryText "#AR-Briefing_CO_Arland_Signal_US"
    }
    SCR_JournalEntry "{646847056DB826B0}" {
     m_iEntryID 5
     m_eJournalEntryType Intel
     m_sCustomEntryName "#AR-RespawnMap_FRAGO_IntelTitle"
     m_sEntryText "#AR-Briefing_CO_Arland_Intel_US"
    }
   }
  }
 }
}